name: CI - Pipeline Informatif

on:
  push:

jobs:
  integration-continue:
    name: Démonstration CI
    runs-on: ubuntu-latest

    env:
      STEP1: "Le code vient d'être poussé sur Github"
    steps:
      - name: Etape 1 - initialisation
        run:
          $echo "Demarage du pipeline d'integration continue"
          echo "STEP1=$STEP1"

